# Generated by Django 3.1.2 on 2022-06-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obj_ev', '0001_initial'),
        ('users', '0002_userc_objs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userc',
            name='objs',
            field=models.ManyToManyField(blank=True, related_name='users_domen', to='obj_ev.ObjEv'),
        ),
    ]
