# Generated by Django 3.1.2 on 2022-06-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uin', models.CharField(default=None, max_length=255)),
                ('Uout', models.CharField(default=None, max_length=255)),
                ('temp', models.CharField(default=None, max_length=255)),
                ('voltage', models.CharField(default=None, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
    ]
