# Generated by Django 3.1.2 on 2022-06-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obj_ev', '0001_initial'),
        ('stats', '0002_stat_domen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='slug',
        ),
        migrations.AlterField(
            model_name='stat',
            name='domen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat_domen', to='obj_ev.objev', verbose_name='Domen'),
        ),
    ]
