# Generated by Django 3.1.2 on 2022-06-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_stat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
